GET http://localhost:3000/cat
Content-Type: application/json
  
###

GET http://localhost:3000/cat/61c8085cdfe77dd4e1f0dbfc
Content-Type: application/json

###

GET http://localhost:3000/cat/parent/:id
Content-Type: application/json

###

POST http://localhost:3000/cat
Content-Type: application/json

{
  "name": "Kuby",
  "age": 4,
  "breed": "Maine"
}

###

DELETE http://localhost:3000/cat/:id
Content-Type: application/json

###

DELETE http://localhost:3000/cat
Content-Type: application/json


